In [37]:
import numpy as np

In [38]:
arr = [47,23,7,17,63,34]
A = np.array(arr)
print("Numpy Array: ",A)

Numpy Array:  [47 23  7 17 63 34]


In [39]:
print("Array: ",A)
print("A[0:3]: ",A[0:3])
print("A[1:]: ",A[1:])
print("A[-5:-3]: ",A[-5:-3])
print("A[-2:]: ",A[-2:])

Array:  [47 23  7 17 63 34]
A[0:3]:  [47 23  7]
A[1:]:  [23  7 17 63 34]
A[-5:-3]:  [23  7]
A[-2:]:  [63 34]


In [40]:
print("Array: ",A)
print("Addition: ",A+5)
print("Subtraction: ",A-5)
print("Multiplication: ",A*5)
print("Division: ",A/5)


Array:  [47 23  7 17 63 34]
Addition:  [52 28 12 22 68 39]
Subtraction:  [42 18  2 12 58 29]
Multiplication:  [235 115  35  85 315 170]
Division:  [ 9.4  4.6  1.4  3.4 12.6  6.8]


In [41]:
print("Array: ",A)
print("Sum: ",np.sum(A))
print("Mean: ",np.mean(A))
print("Max: ",np.max(A))
print("Min: ",np.min(A))

Array:  [47 23  7 17 63 34]
Sum:  191
Mean:  31.833333333333332
Max:  63
Min:  7


In [43]:
print("Array: ",A)
print("A(2X3): \n ",A.reshape(2,3))
print("A(3X2): \n",A.reshape(3,2))

Array:  [47 23  7 17 63 34]
A(2X3): 
  [[47 23  7]
 [17 63 34]]
A(3X2): 
 [[47 23]
 [ 7 17]
 [63 34]]
